[project]
name = "deeper-seek"
version = "0.1.0"
description = "Geospatial similarity search using satellite imagery and Google Earth Engine"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "earthengine-api>=0.1.37",
    "geemap>=0.29.0",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "matplotlib>=3.5.0",
    "jupyter>=1.0.0",
    "folium>=0.14.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
